export enum InfluencerDetails {
    INFLUENCER_BASIC_DETAILS = "INFLUENCER_BASIC_DETAILS",
    INFLUENCER_ACCOUNT_DETAILS = "INFLUENCER_ACCOUNT_DETAILS",
    INFLUENCER_LOCATION_DETAILS = "INFLUENCER_LOCATION_DETAILS",
}

export enum PincodeDetails {
    FETCH_PINCODE_DETAILS = "FETCH_PINCODE_DETAILS",
    FETCH_SUCCEEDED = "FETCH_SUCCEEDED",
    FETCH_FAILED = "FETCH_FAILED",
}

export enum JourneyStatus {
    FETCH_JOURNEY_STATUS = "FETCH_JOURNEY_STATUS",
    FETCH_JOURNEY_STATUS_UPDATE = "FETCH_JOURNEY_STATUS_UPDATE",
    FETCH_JOURNEY_STATUS_SUCCESS = "FETCH_JOURNEY_STATUS_SUCCESS",
    FETCH_JOURNEY_STATUS_FAILURE = "FETCH_JOURNEY_STATUS_FAILURE",
    SET_JOURNEY_STATUS = "SET_JOURNEY_STATUS",
}

export enum AccountDetails {
    FETCH_ACCOUNT_DETAILS = "FETCH_ACCOUNT_DETAILS",
    FETCH_ACCOUNT_DETAILS_UPDATE = "FETCH_ACCOUNT_DETAILS_UPDATE",
    FETCH_ACCOUNT_DETAILS_SUCCESS = "FETCH_ACCOUNT_DETAILS_SUCCESS",
    FETCH_ACCOUNT_DETAILS_FAILURE = "FETCH_ACCOUNT_DETAILS_FAILURE",
    EMPTY_ACCOUNT_DETAILS = "EMPTY_ACCOUNT_DETAILS",
}
